### ISSUE TITLE
iPad and iPad Mini Media Queries with Top-Bar Menu

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP-CSS#10]
Hello, I was wondering how you could display the main menu with off-canvas support used on the mobile screen (e.g. iPhone) for both the iPad and iPad mini. I tried editing foundations.css line 5909 /*Medium Display */ @media to something like @media only screen and (min-width: 48.0625em) but it only gets me half way there. Is there a better way to go about doing this?

Thanks,
Jack

**Comment by JeremyEnglert** [comment]
@jackfearing it is relatively hard to change this in the CSS version (it's really easy to change in the Sass version).

Check out this article from the Foundation forum:
http://foundation.zurb.com/forum/posts/1053-changing-topbar-breakpoint-using-css

The response from Rafi Benkual is probably your best bet. You can download a custom version of Foundation from their website, and then upload these over the Foundation files from Joints.

**Comment by jackfearing** [comment]
How would go about changing it in the sass version? I'm currently using gulp to process my files and I'm pretty sure I could just include that into a task to process the css.

**Comment by JeremyEnglert** [comment]
If you're using the Sass version, check out the _settings.scss file. Line #1465.
