### ISSUE TITLE
What happened to the different media sizes in CSS?

### ISSUE THREAD

**Issue by Adrien-Luxey** [JeremyEnglert/JointsWP-CSS#11]
Hi Jeremy,

I haven't been paying attention, but you removed the media queries for small, medium etc in assets/css/style.css. How are we supposed to style only for medium up, for example?

Thanks,
Adrien

**Comment by JeremyEnglert** [comment]
They were removed from the Sass version in favor of this technique: http://jointswp.com/using-foundation-media-queries-with-sass/

You can easily add your own media queries, here are the Foundation ones: http://foundation.zurb.com/docs/media-queries.html
