### ISSUE TITLE
close html

### ISSUE THREAD

**Issue by martajohnsson** [JeremyEnglert/JointsWP-CSS#7]
Hi, I can't see you close the html tag, the last one in the footer is the closing body tag.

**Comment by JeremyEnglert** [comment]
Hi Martha, HTML5 (and HTML4 for that matter), does not require a closing HTML tag. However, this issue has already been fixed in the Sass version - so I will get it fixed here as well. Nice catch!

**Comment by JeremyEnglert** [comment]
This has been resolved.
