### ISSUE TITLE
script.js not loaded on admin pages ?

### ISSUE THREAD

**Issue by Adrien-Luxey** [JeremyEnglert/JointsWP-CSS#8]
Hi there!

First of all, thanks a lot for your theme! I'm having a lot of fun reading through you huge blocks of welcoming comments, thus improving my Wordpress skills and creating cool designs for different people: life is cool. 
Furthermore, I have been looking for that kind of theme for ages! I ended up tossing SCSS which causes more issues than solutions in my situation, so I'm glad you provided both versions.

Still, I am surprised to see that you only load /library/js/script.js in the non admin pages. This is written the function joints_scripts_and_styles() in /library/joints.php. I can understand that you don't really need Foundation in admin pages, but what about Gravatar ? Plus your comment in script.js says we have to (well, can) add our js code here. I wanted to add jQuery UI datepicker for a custom type in the admin section, and spent a little time figuring it out (finding the right if statement... Don't blame me it's late!).

No big deal, though, I'm mostly being curious.
Thanks again for the theme!
Adrien

**Comment by JeremyEnglert** [comment]
This is pretty normal behavior. If you want to call scripts on the admin pages, you'll want to use admin_enqueue_scripts action.

http://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts
