### ISSUE TITLE
normalize.css should be loaded before foundation.css

### ISSUE THREAD

**Issue by Adrien-Luxey** [JeremyEnglert/JointsWP-CSS#9]
Eyh, it's me again !

Foundation recommends including normalize.css before foundation.css, and I saw that it was for good reasons : normalize overrides foundation's textarea markup if you set it second. It makes a text input and a textarea have different fonts, which is not cool.

Swapping lines 127 and 130 of joints.php seems to do the job.

Regards,
Adrien

**Comment by JeremyEnglert** [comment]
This has been corrected - thanks!

**Comment by Adrien-Luxey** [comment]
Hey!

I saw your brand new update, and I'm just starting a new design. I'll try
to send you some pull requests if I find anything nasty in your code. Or
some neat piece of code if I build anything interesting (not sure you're
interested, though).
But I looks a lot clearer this way already, nice job!
(I'm sticking with the CSS one, SASS brings me more trouble than joy, FYI.)

Still, I really must thank you for all your work. JointsWP is a killer! And
know that I've read through all your comments 2-3 times, I'm a killer too!
For the old design of the site I am rebuilding, I used Required+
Foundation. Featuring... Foundation 3! The dev has be discontinued for a
long time now...
So, really, I don't know how you get the patience to do such a nice job,
but thanks! Don't you have any kind of Donation stuff? I sure could
motivate my client on paying you the Internet for a month, considering that
he will soon have the best fucking news site around thanks to you.

Cheers!
Adrien


2015-06-17 21:12 GMT+02:00 Jeremy Englert <notifications@github.com>:

**Comment by JeremyEnglert** [comment]
Awesome - let me know what you think of the new version! Also, be sure to send over a link when it's done - I'd love to see it.

While your contributions are more than enough of a donation, there is also now a donate page on the JointsWP.com website.

http://jointswp.com/donate/

:+1:

**Comment by Adrien-Luxey** [comment]
If you want to see the one site I did when I left you my ticket, have a
look over here ! http://www.rennesdesbois.fr/

I'm no designer nor graphist, but I had a graphist friend helping me on
this one. The site is about an association in the crazy French city of
Rennes ! Where good beer flows in an endless cycle, alongside with cool
lifestyle and good food!
So, the association board is really small, but we have had quite a good
audience around town!

And I'll keep your donate link safe!

2015-06-18 1:46 GMT+02:00 Jeremy Englert <notifications@github.com>:
